project:
  type: website
  output-dir: docs

website:
  title: "Análise de Dados em Engenharia (Em desenvolvimento!)"
  back-to-top-navigation: true
  navbar: 
    search: true
    right: 
      - text: Autor
        href: autor.qmd
      - text: Contato
        href: contato.qmd
  sidebar:
    style: "docked"
    tools: 
      - icon: linkedin
        href: https://linkedin.com
      - icon: youtube
        href: https://www.youtube.com/@ebartacademy7018
    search: true
    contents:
      - text: Home
        href: index.qmd 
      - section: "Área do Aluno"
        contents:
          - text: "Plano de Ensino"
            href: planoensino.qmd
          - text: "Links Úteis"
            href: linksuteis.qmd
      - section: "Use o R"
        contents:
          - text: "Introdução ao RStudio"
            href: Praticando_R.qmd
          - text: "Estatística Básica na Linguagem R"
            href: statr.qmd
      - section: "Análise de Dados em Engenharia"
        contents:
          - text: "Análise Exploratória de Dados"
            href: aed.qmd
          - text: "Correlação e Covariância"
            href: correlcov.qmd
          - text: "Amostragem"
            href: amostragem.qmd
          - text: "Intervalos Estatísticos"
            href: intervalos.qmd
          - text: "Exercícios Propostos" 
            href: exercicios.qmd
      - section: "Anexos"
        contents:
          - text: "Tabela Z" 
            href: tabelaz.qmd
          - text: "Tabela t de Student" 
            href: tabelat.qmd
          - text: "Tabela Qui-quadrado" 
            href: tabelaqui.qmd
          - text: "Tabela F de Snedecor" 
            href: tabelaf.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

